sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: "garethahealy-github"
    token:
      secure: l9e6qXrZjhM8Sf7fFXSBXaV8ouhBUy8UYu2CfuW5vBSfG+m6Z3gHQyQZMaF21LcG2DbNvwHAoLvc6XzAbvLFNZKOwXGy6oFyoIxoRMy878k3wKch+09FVhUm53/OPwdrXFfU4oSI9reJC+Y8S9w6cGWoW9DFA5IjBNroj3ziKVAySnh77czpFF88d6HO3PY8U4C5Mq9N0HbH5MhXX72ZRgJqLL29H0uP2PgBMzbLoOu4JqelNbtdiy55Egy94HfAKD6wnH6zm87lH6s35Cdic18iolBAmGsbk+UrdL03nQ5ARrgQ8NnSi6/eiIwzHBtz/DX7F3OvvdOyQo+Cp9pJ2B2HocKc3l7gOFfLP1Om8iUygrsLFYwvwu9phmp1stGdl3d3RorUSmnglGZwVNMIK8o0cFc0xeBIFqP9qOEmCn+flCJoqc9Kcdln4Spk6QkEea6IHf1Bc1L6TTi3bxVAqtsO49/cp6clPhD7tskMwvBgB7hDWF7awAp2Z+X78jrEDZ0QG9swfqpdfmW0cLi5s9hsAQcgqpzh/8+lZ0hQdn6iPm0od4ezSta3rz4v7X90qdwtjnlA6+GLGhEy3QBMhEjt5MJGG8mZfAz0f3txxi+nhAMMswS7Fn5v1PD6RzHWCwUnwb9LMg28//ebLVMmGXXtmTKPuOM1pu7TdJXEngI=
env:
  global:
  - secure: PV+6RnajVsSs8onM/zR6Vv8FANT0Br7gVYe8x9oj1Ku0C6W0DTlEKzHvAZXuX0uB23VJF4mwt/HK7/ukOKe/oHaH6HbOYP/tqetaWRlsyY6pcEXW7C2LGqU2CrbAJ6Qh2Pd/FLdDswUEQSroBrc14BQCd+qBIU2BmUbOfxqWdRQNC+u6QJEsoLPeyYTV9/xBdEpmesNRE9ZnaqDSUX9E4W8zongrnGFZr80u9P40duQvpJATlNEnJ4DF2gpuI6R2pDPosxNywa+yS9rbZi7aXlamefg6IqcBh4f4A6T4DB1PXnbNmiY+TAKZ1hZnFF0/7Mz5othrX9wm6VGXpNyaDTtDDmueuIBB9gEsfZk7kSNa7Eyp9OULNJ8vAFv8xnXoZYab2YOoJ1QT+TFQce1lnWVRCDmD+MrUEp71a7DfbH0iiyUP7W7xCOi7YR5h4rPWFLwAzC867evkDdr5a5SGAObjGyZ/Bhro5UMmeSfu93GphGIh5Ld97KVo8YYV5NNZqb/mCu1wc2WY4VEBP5FPY0/m+JqSEfg6W5/vLEmIseSLrJ+PXF70UWo/Yqhih9Y6L3OoswSR3S2vENM+U/7BVXujaAJ9Gri5YtiBUhr7P39njrh4W0cPANCNi5g088+GaI2HjYA4LSceNSU9zfHNeJJ++lQu/sHfQQ+YhN90xbc=
  - secure: CVzpn77/Eb1MGyjLy1pcOA833J0hT6rpegLzn6IeysJjsTjAKUJ24wrcWm/zap7RKAkf9I0jHxIPoSlQV8AULCDT4CNBJqKkvAwcBpQ1SoVQW1w4ZuStR1DNt9O9pY+dIfrV2J7M7dyWzmjeimZz3JXtnqw1m6mgfyl9ifVXTFrM0gIDtgHyul4l9e4sbqL5R0t/EOxXzea2Jrcp8xIkc7gJ9V7tGEfM7QSpIo6bVBMU8kK15hUbcLr8B9n+kdfufXKn6eNNIwvf3ez//kdmyFvZ9w96jkCc51eNTYPVcqEASSFZw6K/yEt7pEWOOvl8S5XgFTAKpjLSdRBBrxX+QIBUnHMoxkk04RoT1d3RmKeI7DFzD6VRq5D9BM79RELJRbl5D5IqpHim0t4ZGCNnGxw0/ogmJQvSAAYcv4hRck27FwqIHPB3eQosgVrzp4RhttVbWS2/eJ80l49yHVcftJOAGwmOpQiYlPE1yp0EXmkJApHgI+VcWmf9tLIaF/nxgVHy/8Y1jkjVFR7nZQGF9Fl0nudoUteFYcLEGInNWsRNPKALKjYrODyCFXxqBt4xWd6NWwI3kGGhTckTBgGgMOgsT+lgWrfq9L20pEe8XreMxAUP6orLozzoVqsTZMBCMbIsWUsS6y7JV0DWCU9w8nYa5aHCvcpDF7cdiExLC0c=
  - secure: ECGJqXORfcbvUkFgIhfSZHKobQ0I92az4ozQDB4ujp6ReSD3vWvtX/jEHcx2PweAenHEACABhHoBsT7npbxuO7kxXdRhrzswEoejGRf5/T9AZzBiGxbBtrBOPP/4KHyHKM6rPQk3FBnV5VOOHIOitYUWXKnbIaAbqzYjP1xgHnUi9VdHXJNKZvLqPLJxqw+VW/NE29rrmnok0Cjo/3IfRFG7+NC1qGf+jkRCqCUlCuYCTUQR/0nDmruVeV+goqYQEOZ2y37PBexlH3uVL4rV6v0/pwRCm5GAq1/dnaf7BUIy4haVCfch+E4mrMPevKdn/L+wZB0KbooqHYiJHIdaMa72PHApkfS/7QQRNIxW9MvDODwGktv3+OzS6CeZJvEE7cpaafk+dSz+UcpQA79rYeGcyXb0065DJfVftiw6SdtrPNSvRSiSd8VFRcspbopR4/QGpY2TFbUJWgXzQ55tk2Q0fJne5zmdiNjyO90AdWPDGGAiHDO6sCuuDr8oLw+VvBO1t6Qh6M0zyOnQ3fVmfZxOroDgKa+2jpx+uPnl8t+kSSjAa2R3F+U++IiAmHj4Isjdxh3vcbZcvX6GItEQo/5GaDIGvoXGCpy1yaKEqyt1m/dMnves/f+NXvTS/guo7X9yO6r7qtsa2DGKXptSnR+dhwVJyjtCT8Ku/t+D/+s=
  - secure: L/cDyK80DvEE8XmhxURNsJaP3HGGE6BHF9toAamDGkrRWeiIxDEhTgk7sAwfig8hELNSikjcstCa0otn3fa0ZEQPjKzPkZuvHwmxONK59avpOClNFGMOFkj/BeC5y2Bzm1ulJ2IijItraPX5Yd6/Ju2bdB2PE9FVYc+Pkp/nfLbJp/NTPcORIj9PvQI8e4mZGaZyijEUxceo2WY9HPqe05j/e7SJfIFcmO3YbPQPrpVycQAKTY8zB9v2BpGf6UWBRnXQexrEA+FvVB0Xs5T4atVmt14KjyV7KPd0HV8lBo60sCm4tlVXyqQpcWV2z1nePi9qxEXnTfA+VNGtXWhlEIIDLl/9LO7edvcXrcfJ6fyFDAbFQXIhLRT8/LA9bJ2m1tSzFnxQulRAExUbfkmS/L1C6RaeLCK1oS0zobSTkIXUmOSPIBhCQu1DYI3HlZqd2yCyyHSE5K7Ayz8eJqRUZgt+52mnM1zSPGtKXC9dmUcYXuqhdSDSVQ58rVe+YmHuXiLkLNKl2Ggaoo90UBNj+wotQmH0AZuAIF+Y1yJDEurNGCibVi295tB845NgT7ABbuEkAknD/Qb64A9i7Yvrf5fK1E04n7LhQ3fuY4Jbd9Q3kNcb3yu7HyTAH0DRfWtccI3k2WZ0zRe5/Dm48hUX1ifKveMXdc/5zQOscUD4Dng=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw dependency:go-offline -B -Prelease-ossrh
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
  - $HOME/.sonar/cache
